name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Clean up old packages
        run: rm -f **/bin/Release/*.nupkg

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          dotnet pack --configuration Release /p:PackageVersion=$VERSION

      - name: Push to NuGet
        run: dotnet nuget push "**/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
